#thanks https://github.com/gquittet/php-mariadb-apache/blob/master/docker-compose.yml

version: "3"

services:
  #to run a command: docker exec -it tabby_db mysql -uroot -p
  db:
    hostname: dbContainer
    image: mariadb
    container_name: tabby_db
    restart: always
    networks:
      - backend
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpasswordhere
      MYSQL_USER: tab_admin
      MYSQL_PASSWORD: controllerofthetabs
      MYSQL_DATABASE: tabby
    ports:
      - 3306:3306

  php-apache:
    hostname: apacheContainer
    build:
      context: ./php-apache-build
    container_name: tabby_web
    restart: always
    networks:
      - backend
      - frontend
    depends_on:
      - db
    volumes:
      - ./DocumentRoot:/var/www/html
    ports:
      - 80:80

  phpmyadmin:
    hostname: phpMyAdminContainer
    image: phpmyadmin/phpmyadmin
    container_name: tabby_admin
    restart: always
    #environment:
    #  MYSQL_ROOT_PASSWORD: supersecretpasswordhere
    #      MYSQL_USER: tab_admin
    #      MYSQL_PASSWORD: controllerofthetabs
    networks:
      - backend
      - frontend
    links:
      - db:db
    depends_on:
      - db
    ports:
      - 8080:80

networks:
  backend:
  frontend:
