#thanks https://github.com/gquittet/php-mariadb-apache/blob/master/docker-compose.yml

version: "3"

services:
  db:
    hostname: dbContainer
    image: mariadb
    #TODO: create needed tables from .sql file on build?
    #https://stackoverflow.com/questions/52074643/how-to-populate-a-mariadb-in-an-docker-container
    container_name: tabit_db
    restart: always
    networks:
      - backend
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci
    volumes: #have a docker volume just for kicks
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpasswordhere
      MYSQL_USER: tab_admin
      MYSQL_PASSWORD: controllerofthetabs
      MYSQL_DATABASE: tabit
    ports:
      - 3306:3306
    #to run a command: docker exec -it tabit_db mysql -uroot -p
  
  php-apache:
    hostname: apacheContainer
    build:
      context: ./docker-php-apache
    container_name: tabit_web
    networks:
      - backend
      - frontend
    depends_on:
      - db
    volumes:
      - ./DocumentRoot:/var/www/html
    ports:
      - 80:80
  
  phpmyadmin:
    hostname: phpMyAdminContainer
    image: phpmyadmin/phpmyadmin
    container_name: tabit_admin
    environment: 
      MYSQL_ROOT_PASSWORD: supersecretpasswordhere
#      MYSQL_USER: tab_admin
#      MYSQL_PASSWORD: controllerofthetabs
    networks:
      - backend
      - frontend
    links:
      - db:db
    depends_on:
      - db
    ports:
      - 8080:80

volumes:
  mariadb:

networks:
  backend:
  frontend:
